Repository cta-observatory/protopipe, pull requests merged in 2022-04, with the labels that each got.

#181 Add benchmarking notebook template
  environment_development.yml
  protopipe/benchmarks/notebooks/notebook_template.ipynb
  protopipe/benchmarks/operations.py
  setup.py
Labels: benchmarks, dev users

#194 Update DOI
  README.rst
  docs/citing.rst
Labels: maintenance

#193 Add badge for Continuous Development (CD)
  README.rst
  docs/index.rst
Labels: maintenance

#196 Fix version switcher URL for latest version
  docs/_static/switcher.json
  docs/contribute/instructions.rst
Labels: documentation, fix

#190 update changelog with v0.5.0 info
  docs/CHANGELOG.rst
Labels: maintenance
